---

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "Installing Node Dependencies"
  shell: |
    cd ~/
    npm install
    
- name: "Executing Node app with PM2"
  shell: |
    pm2 stop default
    pm2 start npm -- start
