---

- name: Creates directory
  file:
    path: ~/backendtmp
    state: directory

   
- name: "Unarchive backend files"
  unarchive:
    src: /.circleci/ansible/artifact.tar.gz
    dest: ~/backendtmp

- name: "Installing Node Dependencies"
  shell: |
    cd /.circleci/backend/
    npm install
    
- name: "Executing Node app with PM2"
  shell: |
    pm2 stop default
    pm2 start npm -- start
