---

- name: "Unarchive backend files"
  become: yes
  unarchive:
    src: /.circleci/backend/artifact.tar.gz
    dest: /.circleci/backend/

- name: "Installing Node Dependencies"
  shell: |
    cd /.circleci/backend/
    npm install
    
- name: "Executing Node app with PM2"
  shell: |
    pm2 stop default
    pm2 start npm -- start
